# Generated by Django 4.1.7 on 2023-03-06 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0002_alter_college_image_alter_college_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='image',
            field=models.ImageField(help_text='Select image of size 510x300', upload_to='images/college'),
        ),
        migrations.AlterField(
            model_name='college',
            name='logo',
            field=models.ImageField(help_text='Select image of size 75x75', upload_to='images/college/logos'),
        ),
        migrations.AlterField(
            model_name='collegeimages',
            name='image',
            field=models.ImageField(help_text='Select image of size 280x175', upload_to='images/collegeImages'),
        ),
    ]
